function fill_inv()
	turtle.select(1)
	turtle.suck()
	turtle.select(2)
	turtle.suck()
	turtle.select(3)
	turtle.suck()
	turtle.select(4)
	turtle.suck()
	turtle.select(5)
	turtle.suck()
	turtle.select(6)
	turtle.suck()
	turtle.select(7)
	turtle.suck()
	turtle.select(8)
	turtle.suck()
	turtle.select(9)
	turtle.suck()
	turtle.select(10)
	turtle.suck()
	turtle.select(11)
	turtle.suck()
	turtle.select(12)
	turtle.suck()
	turtle.select(13)
	turtle.suck()
	turtle.select(14)
	turtle.suck()
	turtle.select(15)
	turtle.suck()
	turtle.select(16)
	turtle.suck()
end

function dump_inv()
	turtle.select(1)
	turtle.dropDown()
	turtle.select(2)
	turtle.dropDown()
	turtle.select(3)
	turtle.dropDown()
	turtle.select(4)
	turtle.dropDown()
	turtle.select(5)
	turtle.dropDown()
	turtle.select(6)
	turtle.dropDown()
	turtle.select(7)
	turtle.dropDown()
	turtle.select(8)
	turtle.dropDown()
	turtle.select(9)
	turtle.dropDown()
	turtle.select(10)
	turtle.dropDown()
	turtle.select(11)
	turtle.dropDown()
	turtle.select(12)
	turtle.dropDown()
	turtle.select(13)
	turtle.dropDown()
	turtle.select(14)
	turtle.dropDown()
	turtle.select(15)
	turtle.dropDown()
	turtle.select(16)
	turtle.dropDown()
end

running = true

while running do
	if turtle.detect() then
		dump_inv()
		fill_inv()
		turtle.turnLeft()
		turtle.turnLeft()
	while turtle.detect() == false do
		turtle.forward()
	end
end
